version: '3'
services:

  #tomcat Service
 appserver:
  build: 
   context: ./appserver
  container_name: appserver
  restart: unless-stopped
  tty: true
  expose:
     - 8080
  environment:
     VIRTUAL_HOST: app.rddhiapps.com
  volumes:
    - './tomcat/webapps:/usr/local/tomcat/webapps'
 staticwebserver:
  build:
    context: ./staticwebserver
  container_name: staticwebserver
  restart: unless-stopped
  tty: true
  environment:
    VIRTUAL_HOST: static.rddhiapps.com
  expose:
     - 80
  volumes:
     - './static:/usr/share/nginx/html'
       #volumes:
       #- 'html/:/var/www/html' 
       #Nginx Service
 webserver:
  build:
    context: ./webserver
  container_name: webserver
  restart: unless-stopped
  tty: true
  ports:
    - "80:80"
    - "8080:8080"
  volumes:
    - './conf/nginx.conf:/etc/nginx/nginx.conf'
    - '/var/run/docker.sock:/tmp/docker.sock:ro'

  
 #Docker Networks
networks:
  default:
    external:
      name: webserver
